# Generated by Django 2.2.16 on 2022-01-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220128_2220'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_prevent_self_follow',
        ),
    ]
